server:
  port: 8084

spring:
  application:
    name: bff-service
  kafka:
    bootstrap-servers: localhost:9092
  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSSSSS
    time-zone: UTC
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      adjust-dates-to-context-time-zone: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

services:
  user-service: user-service
  account-service: account-service
  transaction-service: transaction-service
