server:
  port: 8084

spring:
  application:
    name: bff-service
  kafka:
    bootstrap-servers: localhost:9092

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

services:
  user-service: user-service
  account-service: account-service
  transaction-service: transaction-service
